tg/controllers/__init__.py
tg/models/__init__.py
tg/views/__init__.py

Fix index error when going over last chat
Remove loops that might cause msg duplicationn

Catch exceptions in update_handler

---

tg/controllers/__init__.py
tg/models/__init__.py
tg/utils.py
tg/views/__init__.py

Added:
- `gg` vim like shortcut for jumping to the beginning of the chats. note, I didn't touch `G` wchih should jump to the end of the chats, because we may want to add some chats preloading logic.
- added repeat factor support so the following shortcuts could work `4j`, `3k`, etc.

added gg, 4j, 3k keybinding support

---

tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py

Listen for `updateChatLastMessage` and update chat title based on that

Dynamically update chat titles

---

tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py

Currently, when I am sending a new message I am seeing msg duplication in the chat. 
This PR fixes this.
Here is a flow when sending new message:
1. Submits new message
2. client pushs msgs to the Telegram
3. `updateNewMessage` is raised, client updating UI with new message from it
4. `updateMessageSendSucceeded` is raised, which means that message sent was succeeded. This message discard msg id from the previous `updateNewMessage` message, so we need remove it.

Correcty handle sending msgs

---

.gitignore
tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/views/__init__.py

- improve some function namings
- allow to delete selected msg from the chat by `d` keypress
- update view to handle situation when there is a chat with no message(all were deleted)
further ideas:
- when sending delete request to the telegram, API responds back with `updateDeleteMessages`. in order to be more robust, we could remove message from UI only whem ACK from telegram side was received in form of the `updateDeleteMessages` message.
- message removal is pretty destructive operation so we may want to also add user conformation before msg removal.

Support msg deleting from chats

---

tg/models/__init__.py

- fix selected chat msgs was not fully loaded
- fix issue when only 1 msg was loaded (see https://github.com/tdlib/td/issues/168)

Fix chat msgs loading issues

---

tg/controllers/__init__.py
tg/models/__init__.py

I rewrote to use one functions instead of useless wrappers and also updated keybindings to make them more consistent through ui

Update keybindings and remove some useless code

---

tg/colors.py
tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/utils.py
tg/views/__init__.py

- Auto added type annotation. Manually fixed some of them
- Fixed some existing code issues in 2nd commit

Add type annotations

---

README.md
tg/colors.py
tg/config.py
tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/msg.py
tg/utils.py
tg/views/__init__.py

- introduced new entity MsgProxy: it adds helpful fields to make writing less code
- extended lib with new api call download_file
- rewrote msg handling
- rewrote msg parsing, to have one function for chats and msgs
- open msg with `l` (open should be installed, mailcap support in next patches)
- added update_file handler for updating file download state
- removed tdlib logging to stdin

Add ability to download and open files

---

README.md
tg/config.py
tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/utils.py
tg/views/__init__.py

- Sort imports
- Fix black formatting
- Add base functionality to send files

send files

---

tg/controllers/__init__.py
tg/views/__init__.py

Mark muted chats
Fix bug with msgs longer than status's width
Add vertical line separtor between chats and msgs
Update chat view

Do not notify new msgs if chat is muted

---

tg/controllers/__init__.py
tg/models/__init__.py
tg/views/__init__.py

- add ranger like msg scrolling support
- truncating long message to the one line, for simplifity

Add msg scrolling

---

tg/controllers/__init__.py
tg/models/__init__.py
tg/utils.py
tg/views/__init__.py

- Add chat scrolling
- Fix load chat function based on tdlib [issue](https://github.com/tdlib/td/issues/56#issuecomment-364221408)
-  small view refactoring
- increased logs size to 10MB
- added shortcut for debbuger for dev purposes 
Also see https://core.telegram.org/tdlib/getting-started#getting-the-lists-of-chats

Chats scrolling

---

tg/controllers/__init__.py
tg/models/__init__.py
tg/views/__init__.py

Process next updates:
- "updateMessageContent"
- "updateChatIsPinned"
- "updateChatIsMarkedAsUnread"
- "updateChatReadInbox"
- "updateChatTitle"
- "updateChatLastMessage"
- "updateChatDraftMessage"
- "updateChatOrder"

Proccess msg & chat updates

---

tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/msg.py
tg/views/__init__.py

Adding support for openMessageContent msg.
Voice msg was listened, video note was viewed, self destructing msg should start ttl, etc.
updateMessageContentOpened will come and we should update accordingly base on the type of msg.
Only voice and video notes implemented support currently

Add support for openMessageContent and updateMessageContentOpened

---

tg/controllers/__init__.py
tg/main.py
tg/models/__init__.py
tg/views/__init__.py

Next flags supported:
edited, new, unseen, failed, pending
When navigating through msgs, mark them as read

Show message flags

---

tg/controllers.py
tg/models.py
tg/msg.py
tg/tdlib.py
tg/views.py

- Add forward msg functionality and multiple msgs selection

Add forward msg functionality and multiple msgs selection

---

tg/config.py
tg/controllers.py
tg/models.py
tg/tdlib.py

- add "r" keybinding for inline reply
- and "R" for long reply. each line of the replied msg will be wrapped with `# > ` prefix

Add msg reply support

---

tg/config.py
tg/controllers.py
tg/main.py
tg/update_handlers.py
tg/utils.py

- Update record_cmd
- Fix new config usage
- Rewrite config file
New config file allows us to use such cool things, like keeping secret key and phone number in pass or other password manager.
```
import os
def get_pass(key):
return os.popen("pass show {} | head -n 1".format(key)).read().strip()
PHONE = get_pass("i/telegram-phone")
ENC_KEY = get_pass("i/telegram-enc-key")
LOG_LEVEL = "DEBUG"
TDLIB_PATH = "/usr/local/Cellar/tdlib/1.6.0/lib/libtdjson.dylib"
NOTIFY_CMD = '/usr/local/bin/terminal-notifier -title "{title}" -subtitle "{subtitle}" -message "{msg}" -appIcon "{icon_path}" -sound default -execute \'/Applications/kitty.app/Contents/MacOS/kitty @ --to unix:/tmp/kitty focus-tab --no-response -m title:tg\''
RECORD_CMD = "ffmpeg -f avfoundation -i \":0\" -ar 22050 -b:a 32k '{file_path}'" …
```

Rewrite config

---

tg/utils.py

I have error on master:
```
FileNotFoundError: [Errno 2] No such file or directory: 'xclip -selection c'
```

fix copy cmd

---

tg/config.py
tg/controllers.py
tg/main.py
tg/update_handlers.py
tg/utils.py

- Fix notification: do not notify if char archived and muted
- Add stderr logging and log path
- Do curses draw in one thread

fix notify

---

tg/controllers.py
tg/models.py
tg/tdlib.py
tg/update_handlers.py

* Added edit handler which updates edit_date of the message and adds label `edited` to it
* Rename methods to match original ones (easier to find)

Add msg edited handler

---

tg/main.py
tg/models.py
tg/update_handlers.py
tg/utils.py

- Decrease esc delay: it can be noticed, when multiple msgs selected and pressed esc key
- Refactor update_msg method to match update_chat

Decrese esc delay

---

README.md
pyproject.toml
tg/__init__.py
tg/config.py
tg/main.py
tg/utils.py

- Version 0.0.3
- Initialize config on first run

 Release 0.0.3

---

tg/controllers.py
tg/models.py

- Check if msg can be sent in current chat
- Check if msg can be deleted
- Check if msg can be forwarded

Add checks for sending, deleting, forwarding

---

README.md
tg/config.py
tg/controllers.py
tg/main.py
tg/models.py
tg/update_handlers.py
tg/utils.py
tg/views.py

Rotate logs
Add ability to configure flags representation

Add users status in chat flags

---

tg/views.py

- fix emojis in chat flags
- fix emojis in chat name

Fix layout problems due to emojis in ChatView

---

tg/config.py

I accidentally forgot to add the country code when attempting to login, so i added a check to ensure end users insert their country codes

Requesting country code when the user forgets it

---

README.md

Mention about AUR package in the README 
See https://github.com/paul-nameless/tg/issues/87

Add AUR package info to README

---

README.md
tg/main.py
tg/models.py
tg/utils.py
tg/views.py

This feature is useful for me and this is what does official client.

Show unseen flag in chat pane

---

tg/config.py

Change default ffmpeg cmd for Linux per request in the https://github.com/paul-nameless/tg/issues/86

Change default ffmpeg cmd for Linux

---

tg/models.py
tg/msg.py
tg/update_handlers.py
tg/views.py

remove msgs

---

README.md
tg/colors.py
tg/config.py
tg/utils.py
tg/views.py

Draw users with different colors

---

tg/models.py
tg/update_handlers.py

This bug was a reason for lags in the client: when messages would disappear suddenly or you won't be able to send new ones.

Fix bug in update handler decorator

---

tg/controllers.py
tg/models.py
tg/tdlib.py
tg/views.py

-  show user name in chat preview
- show user name for action label (tom is typing...)

Show last msg sender user name in group chat preview

---

tg/msg.py
tg/update_handlers.py
tg/views.py

- preview poll. 
- poll actions(e.g votes) will be added later

View polls

---

tg/update_handlers.py

https://github.com/tdlib/td/issues/905

Fix disappearing msgs

---

tg/controllers.py

Expand user when getting file path

---

readme.md

128: Update readme with correct configuration

---

readme.md
tg/config.py
tg/controllers.py
tg/models.py
tg/update_handlers.py
tg/utils.py
tg/views.py

File picker

---

tg/models.py
tg/tdlib.py

Parse text formatting when sending
#131

When entered markdown formatted text, parse it to display propely on official clients

---

tg/controllers.py
tg/models.py
tg/tdlib.py
tg/views.py

- `/` searches chats by sending request to tdlib
- `n` and `N` are used to cycle between founded chats

Contacts search

---

tg/controllers.py

Do not draw status panel: it conflicts with another thread

---

.gitignore
pyproject.toml
readme.md
setup.py

- use setuptool instead of flit to remove `flit` as extra dependency during packaging

add setup.py

---

readme.md

Add phone number information

---

readme.md
tg/config.py
tg/controllers.py
tg/models.py
tg/tdlib.py
tg/utils.py
tg/views.py

- Create new chat
- Implement creating new group and secret chat, close secret chat when deleted to prevent showing again after restart
(#150)

Implement creating new group and secret chat ( #150)

---

tg/config.py
tg/utils.py

Create directory for logs if missing

---

readme.md

* Change from telegram-tg-git to telegram-tg
* Add hint for developement version (telegram-tg-git)

Change AUR package to version following releases

---

readme.md
tg/controllers.py
tg/models.py
tg/tdlib.py

The main purpose of this patch is to be able to see encryption key of secret chats. Also, in the future showing chat members or chat files might be implemented.

Show chat info with <c> shortcut in msg panel

---

readme.md
tg/config.py
tg/utils.py

Set custom path to mailcap file

---

readme.md
tg/views.py

Add seen flag

---

readme.md
tg/config.py
tg/controllers.py
tg/models.py

Add copy to download dir keybinding

---

.github/workflows/main.yml
tg/controllers.py
tg/msg.py
tg/tdlib.py
tg/utils.py
tg/views.py

Markup metadata sample: 
```
...,
{
"reply_markup": {
"@type": "replyMarkupInlineKeyboard",
"rows": [
[
{
"@type": "inlineKeyboardButton",
"text": "👍 538",
"type": {
"@type": "inlineKeyboardButtonTypeCallback",
"data": "MTo0bjdlOTlleHFncg=="
}
},
{
"@type": "inlineKeyboardButton",
"text": "👎 55",
"type": {
"@type": "inlineKeyboardButtonTypeCallback",
"data": "Mjo0bjdlOTlleHFncg=="
}
}
],
[
{
"@type": "inlineKeyboardButton",
"text": "Rating",
"type": {
"@type": "inlineKeyboardButtonTypeUrl",
"url": "https://profunctor.io/rating"
}
},
{
"@type": "inlineKeyboardButton",
"text": "Jobs",
"type": {
"@type": "inlineKeyboardButtonTypeUrl",
"url": "https://profunctor.io/jobs"
}
}
]
]
}
}
```
for post like this
will be displayed as

Show reply markup

---

tg/controllers.py
tg/views.py

before
after <img width="737" alt="image" src="https://user-images.githubusercontent.com/9078927/96337501-4c843580-1090-11eb-8e9d-afe8e48083f9.png">

Fix attached msg photos layout

---

tg/controllers.py
tg/tdlib.py
tg/utils.py
tg/views.py

Quote filename path for mailcap

---

pyproject.toml
setup.py

Bump python-telegram version

---

tg/views.py

Move cursor to the correct position for unicode characters when input msg

---

tg/views.py

Fix new msg not shown

---

tg/models.py

For bots, show status 'bot' instead of 'online'

show bot status

---

tg/controllers.py
tg/models.py
tg/msg.py
tg/views.py

Update to TDLib 1.7.10

---

tg/utils.py

Fixes: https://github.com/paul-nameless/tg/issues/270

mitigation for CVE-2015-20107
